version: 2

sources:
  - name: raw
    schema: raw_data_circle
    tables:
      - name: sales
        identifier: raw_cc_sales
      - name: stock
        identifier: raw_cc_stock
        columns:
          - name: model
            tests:
              - not_null
          - name: size
            tests:
              - not_null
          - name: color
            tests:
              - not_null
              - notcolor
